#!/bin/bash
# OpenClaw Gateway Autostart Setup Script for macOS
# Usage: ./setup-macos.sh [--use-proxy] [--proxy-port PORT]

set -e

# Default configuration
USE_PROXY=false
PROXY_PORT="7890"
PROXY_WAIT=20
PROXY_RETRIES=8
PROXY_RETRY_DELAY=5

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --use-proxy)
            USE_PROXY=true
            shift
            ;;
        --proxy-port)
            PROXY_PORT="$2"
            shift 2
            ;;
        --proxy-wait)
            PROXY_WAIT="$2"
            shift 2
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Configuration
OPENCLAW_DIR="$HOME/.openclaw"
LOGS_DIR="$OPENCLAW_DIR/logs"
LAUNCHER_SCRIPT="$OPENCLAW_DIR/gateway-launcher.sh"
PLIST_FILE="$HOME/Library/LaunchAgents/com.openclaw.gateway.plist"

echo ""
echo "========================================"
echo "  OpenClaw Gateway Autostart Setup"
echo "  Platform: macOS"
echo "========================================"
echo ""

# ===== Step 1: Check Prerequisites =====
echo "[Step 1/5] Checking prerequisites..."

if ! command -v openclaw &> /dev/null; then
    echo "  ERROR: openclaw CLI not found!"
    echo "  Please install: npm install -g openclaw"
    exit 1
fi
echo "  OK: openclaw found at $(which openclaw)"

# ===== Step 2: Create Directories =====
echo "[Step 2/5] Creating directories..."

mkdir -p "$OPENCLAW_DIR"
mkdir -p "$LOGS_DIR"
echo "  OK: Directories created"

# ===== Step 3: Create Launcher Script =====
echo "[Step 3/5] Creating launcher script..."

if [ "$USE_PROXY" = true ]; then
    cat > "$LAUNCHER_SCRIPT" << 'SCRIPT_EOF'
#!/bin/bash
# OpenClaw Gateway Launcher (with proxy check)
# Generated by setup-macos.sh

OPENCLAW_DIR="{{OPENCLAW_DIR}}"
LOGS_DIR="{{LOGS_DIR}}"
PROXY_PORT="{{PROXY_PORT}}"
PROXY_WAIT={{PROXY_WAIT}}
PROXY_RETRIES={{PROXY_RETRIES}}
PROXY_RETRY_DELAY={{PROXY_RETRY_DELAY}}

cd "$OPENCLAW_DIR"

# Kill existing gateway processes
pkill -f "openclaw gateway" 2>/dev/null || true
sleep 3

# Wait for proxy
sleep $PROXY_WAIT

proxy_ready=false
retry_count=0

while [ "$proxy_ready" = false ] && [ $retry_count -lt $PROXY_RETRIES ]; do
    if curl -x "http://127.0.0.1:$PROXY_PORT" -s --connect-timeout 5 "https://api.telegram.org" > /dev/null 2>&1; then
        proxy_ready=true
    else
        retry_count=$((retry_count + 1))
        sleep $PROXY_RETRY_DELAY
    fi
done

if [ "$proxy_ready" = false ]; then
    sleep 10
fi

# Start gateway
LOG_FILE="$LOGS_DIR/gateway-$(date +%Y-%m-%d).log"
openclaw gateway start >> "$LOG_FILE" 2>&1 &
SCRIPT_EOF
else
    cat > "$LAUNCHER_SCRIPT" << 'SCRIPT_EOF'
#!/bin/bash
# OpenClaw Gateway Launcher (no proxy)
# Generated by setup-macos.sh

OPENCLAW_DIR="{{OPENCLAW_DIR}}"
LOGS_DIR="{{LOGS_DIR}}"

cd "$OPENCLAW_DIR"

# Kill existing gateway processes
pkill -f "openclaw gateway" 2>/dev/null || true
sleep 3

# Start gateway
LOG_FILE="$LOGS_DIR/gateway-$(date +%Y-%m-%d).log"
openclaw gateway start >> "$LOG_FILE" 2>&1 &
SCRIPT_EOF
fi

# Replace placeholders
sed -i '' "s|{{OPENCLAW_DIR}}|$OPENCLAW_DIR|g" "$LAUNCHER_SCRIPT"
sed -i '' "s|{{LOGS_DIR}}|$LOGS_DIR|g" "$LAUNCHER_SCRIPT"
sed -i '' "s|{{PROXY_PORT}}|$PROXY_PORT|g" "$LAUNCHER_SCRIPT"
sed -i '' "s|{{PROXY_WAIT}}|$PROXY_WAIT|g" "$LAUNCHER_SCRIPT"
sed -i '' "s|{{PROXY_RETRIES}}|$PROXY_RETRIES|g" "$LAUNCHER_SCRIPT"
sed -i '' "s|{{PROXY_RETRY_DELAY}}|$PROXY_RETRY_DELAY|g" "$LAUNCHER_SCRIPT"

chmod +x "$LAUNCHER_SCRIPT"
echo "  OK: Created $LAUNCHER_SCRIPT"

# ===== Step 4: Create LaunchAgent =====
echo "[Step 4/5] Creating LaunchAgent..."

cat > "$PLIST_FILE" << PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.openclaw.gateway</string>
    <key>ProgramArguments</key>
    <array>
        <string>$LAUNCHER_SCRIPT</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <false/>
    <key>StandardOutPath</key>
    <string>$LOGS_DIR/launchd-stdout.log</string>
    <key>StandardErrorPath</key>
    <string>$LOGS_DIR/launchd-stderr.log</string>
</dict>
</plist>
PLIST_EOF

echo "  OK: Created $PLIST_FILE"

# ===== Step 5: Load LaunchAgent =====
echo "[Step 5/5] Loading LaunchAgent..."

# Unload if exists
launchctl unload "$PLIST_FILE" 2>/dev/null || true

# Load
launchctl load "$PLIST_FILE"
echo "  OK: LaunchAgent loaded"

echo ""
echo "========================================"
echo "  Setup Complete!"
echo "========================================"
echo ""
echo "Configuration:"
echo "  Use Proxy: $USE_PROXY"
if [ "$USE_PROXY" = true ]; then
    echo "  Proxy Port: $PROXY_PORT"
    echo "  Proxy Wait: ${PROXY_WAIT}s + ${PROXY_RETRIES} retries"
fi
echo ""
echo "Files:"
echo "  Launcher: $LAUNCHER_SCRIPT"
echo "  Plist: $PLIST_FILE"
echo "  Logs: $LOGS_DIR"
echo ""
echo "Commands:"
echo "  Start:  launchctl start com.openclaw.gateway"
echo "  Stop:   launchctl stop com.openclaw.gateway"
echo "  Status: launchctl list | grep openclaw"
echo ""
echo "Gateway will start automatically on next login."
