#Requires -RunAsAdministrator
# OpenClaw Gateway Autostart Setup Script for Windows
# Usage: powershell -ExecutionPolicy Bypass -File setup-windows.ps1

param(
    [switch]$UseProxy = $false,            # Enable proxy health check
    [string]$ProxyPort = "7890",            # HTTP proxy port
    [int]$ProxyWaitSeconds = 20,            # Initial wait for proxy
    [int]$ProxyMaxRetries = 8,              # Max proxy check retries
    [int]$ProxyRetryDelay = 5               # Seconds between retries
)

$ErrorActionPreference = "Stop"

# ===== Configuration =====
$OpenClawDir = "$env:USERPROFILE\.openclaw"
$LogsDir = "$OpenClawDir\logs"
$VbsFile = "$OpenClawDir\gateway-hidden.vbs"
$TaskName = "OpenClaw Gateway"

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  OpenClaw Gateway Autostart Setup" -ForegroundColor Cyan
Write-Host "  Platform: Windows" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# ===== Step 1: Check Prerequisites =====
Write-Host "[Step 1/5] Checking prerequisites..." -ForegroundColor Yellow

# Check if openclaw is installed
$OpenClawCmd = Get-Command openclaw -ErrorAction SilentlyContinue
if (-not $OpenClawCmd) {
    Write-Host "  ERROR: openclaw CLI not found!" -ForegroundColor Red
    Write-Host "  Please install: npm install -g openclaw" -ForegroundColor Yellow
    exit 1
}
Write-Host "  OK: openclaw found at $($OpenClawCmd.Source)" -ForegroundColor Green

# Check if gateway.cmd exists
$GatewayCmd = "$OpenClawDir\gateway.cmd"
if (-not (Test-Path $GatewayCmd)) {
    Write-Host "  Creating gateway.cmd..." -ForegroundColor Yellow
    @"
@echo off
cd /d "$OpenClawDir"
openclaw gateway start
"@ | Out-File -FilePath $GatewayCmd -Encoding ASCII
}
Write-Host "  OK: gateway.cmd ready" -ForegroundColor Green

# ===== Step 2: Create Directories =====
Write-Host "[Step 2/5] Creating directories..." -ForegroundColor Yellow

if (-not (Test-Path $OpenClawDir)) {
    New-Item -ItemType Directory -Path $OpenClawDir -Force | Out-Null
}
if (-not (Test-Path $LogsDir)) {
    New-Item -ItemType Directory -Path $LogsDir -Force | Out-Null
}
Write-Host "  OK: Directories created" -ForegroundColor Green

# ===== Step 3: Create VBS Launcher =====
Write-Host "[Step 3/5] Creating hidden launcher..." -ForegroundColor Yellow

if ($UseProxy) {
    # VBS with proxy health check
    $VbsContent = @'
' OpenClaw Gateway Hidden Launcher (with proxy check)
' Generated by setup-windows.ps1

Set WshShell = CreateObject("WScript.Shell")
Set fso = CreateObject("Scripting.FileSystemObject")

WshShell.CurrentDirectory = "{{OPENCLAW_DIR}}"

' Kill existing Gateway processes
On Error Resume Next
Set colProcesses = GetObject("winmgmts:").ExecQuery("SELECT * FROM Win32_Process WHERE Name='node.exe'")
For Each objProcess In colProcesses
    cmdLine = LCase(objProcess.CommandLine)
    If InStr(cmdLine, "openclaw") > 0 And InStr(cmdLine, "gateway") > 0 Then
        objProcess.Terminate()
    End If
Next
On Error GoTo 0
WScript.Sleep 3000

' Wait for proxy
WScript.Sleep {{PROXY_WAIT}}000

proxyReady = False
maxRetries = {{PROXY_RETRIES}}
retryCount = 0

Do While Not proxyReady And retryCount < maxRetries
    Set http = CreateObject("MSXML2.XMLHTTP")
    On Error Resume Next
    http.SetProxy 2, "127.0.0.1:{{PROXY_PORT}}", ""
    http.Open "GET", "https://api.telegram.org", False
    http.setTimeouts 5000, 5000, 5000, 5000
    http.Send
    If Err.Number = 0 Then
        proxyReady = True
    End If
    On Error GoTo 0

    If Not proxyReady Then
        retryCount = retryCount + 1
        WScript.Sleep {{PROXY_RETRY_DELAY}}000
    End If
Loop

If Not proxyReady Then
    WScript.Sleep 10000
End If

' Start Gateway
currentDate = Year(Now) & "-" & Right("0" & Month(Now), 2) & "-" & Right("0" & Day(Now), 2)
logFile = "{{LOGS_DIR}}\gateway-" & currentDate & ".log"

If Not fso.FolderExists("{{LOGS_DIR}}") Then
    fso.CreateFolder("{{LOGS_DIR}}")
End If

command = "cmd /c gateway.cmd >> """ & logFile & """ 2>&1"
WshShell.Run command, 0, False
'@
} else {
    # VBS without proxy check (simpler)
    $VbsContent = @'
' OpenClaw Gateway Hidden Launcher (no proxy)
' Generated by setup-windows.ps1

Set WshShell = CreateObject("WScript.Shell")
Set fso = CreateObject("Scripting.FileSystemObject")

WshShell.CurrentDirectory = "{{OPENCLAW_DIR}}"

' Kill existing Gateway processes
On Error Resume Next
Set colProcesses = GetObject("winmgmts:").ExecQuery("SELECT * FROM Win32_Process WHERE Name='node.exe'")
For Each objProcess In colProcesses
    cmdLine = LCase(objProcess.CommandLine)
    If InStr(cmdLine, "openclaw") > 0 And InStr(cmdLine, "gateway") > 0 Then
        objProcess.Terminate()
    End If
Next
On Error GoTo 0
WScript.Sleep 3000

' Start Gateway
currentDate = Year(Now) & "-" & Right("0" & Month(Now), 2) & "-" & Right("0" & Day(Now), 2)
logFile = "{{LOGS_DIR}}\gateway-" & currentDate & ".log"

If Not fso.FolderExists("{{LOGS_DIR}}") Then
    fso.CreateFolder("{{LOGS_DIR}}")
End If

command = "cmd /c gateway.cmd >> """ & logFile & """ 2>&1"
WshShell.Run command, 0, False
'@
}

# Replace placeholders
$VbsContent = $VbsContent -replace "\{\{OPENCLAW_DIR\}\}", $OpenClawDir
$VbsContent = $VbsContent -replace "\{\{LOGS_DIR\}\}", $LogsDir
$VbsContent = $VbsContent -replace "\{\{PROXY_PORT\}\}", $ProxyPort
$VbsContent = $VbsContent -replace "\{\{PROXY_WAIT\}\}", $ProxyWaitSeconds
$VbsContent = $VbsContent -replace "\{\{PROXY_RETRIES\}\}", $ProxyMaxRetries
$VbsContent = $VbsContent -replace "\{\{PROXY_RETRY_DELAY\}\}", $ProxyRetryDelay

$VbsContent | Out-File -FilePath $VbsFile -Encoding ASCII
Write-Host "  OK: Created $VbsFile" -ForegroundColor Green

# ===== Step 4: Create Scheduled Task =====
Write-Host "[Step 4/5] Creating scheduled task..." -ForegroundColor Yellow

# Remove existing task if present
$ExistingTask = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($ExistingTask) {
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
    Write-Host "  Removed existing task" -ForegroundColor Gray
}

# Create new task
$Action = New-ScheduledTaskAction -Execute "wscript.exe" -Argument "`"$VbsFile`"" -WorkingDirectory $OpenClawDir
$Trigger = New-ScheduledTaskTrigger -AtLogon
$Settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBattery -DontStopIfGoingOnBattery -StartWhenAvailable -ExecutionTimeLimit 0

Register-ScheduledTask -TaskName $TaskName -Action $Action -Trigger $Trigger -Settings $Settings -RunLevel Highest -Force | Out-Null
Write-Host "  OK: Created scheduled task '$TaskName'" -ForegroundColor Green

# ===== Step 5: Verify =====
Write-Host "[Step 5/5] Verifying installation..." -ForegroundColor Yellow

$Task = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($Task -and $Task.State -eq "Ready") {
    Write-Host "  OK: Task is ready" -ForegroundColor Green
} else {
    Write-Host "  ERROR: Task verification failed" -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Green
Write-Host "  Setup Complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""
Write-Host "Configuration:" -ForegroundColor Cyan
Write-Host "  Use Proxy: $UseProxy"
if ($UseProxy) {
    Write-Host "  Proxy Port: $ProxyPort"
    Write-Host "  Proxy Wait: ${ProxyWaitSeconds}s + ${ProxyMaxRetries} retries"
}
Write-Host ""
Write-Host "Files:" -ForegroundColor Cyan
Write-Host "  VBS Launcher: $VbsFile"
Write-Host "  Logs: $LogsDir\gateway-YYYY-MM-DD.log"
Write-Host ""
Write-Host "Commands:" -ForegroundColor Cyan
Write-Host "  Start now:  Start-ScheduledTask -TaskName '$TaskName'"
Write-Host "  Stop:       schtasks /End /TN '$TaskName'"
Write-Host "  Status:     Get-ScheduledTask -TaskName '$TaskName'"
Write-Host ""
Write-Host "Gateway will start automatically on next login." -ForegroundColor Green
